# Generated by Django 3.2.7 on 2021-09-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
