# Generated by Django 3.2.7 on 2021-09-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
